### ISSUE TITLE
What is the point of this repository?

### ISSUE THREAD

**Issue by wjk** [Microsoft/vcrt-forwarders#1]
What the title says, really. This repo doesn't help much with true app-local (portable xcopy-deploy) deployment of the CRT, as this repo contains no actual code, only export forwarders. When I need to do true portable CRT deployment, I copy the applicable DLLs out of the VC\Redist folder in my VS install.

Besides, IIRC the `*_app.dll` files contain only UWP-compatible APIs. This would make the stubs in this repository and the real implementations being forwarded to incompatible, potentially causing Store submission failure if used. Some clarification on how this code is useful would be appreciated. Thanks!

**Comment by ocalvo** [comment]
This component is meant to be used by unpackaged Win32 projects that use components that depend on the CRT. As such this should never be used in a Store package project.

**Comment by Huios** [comment]
Have a look at this blog post for more details on usage: https://blogs.windows.com/buildingapps/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/
