### ISSUE TITLE
Using a custom Configuration doesn't work with VCRT Forwarders

### ISSUE THREAD

**Issue by Austin-Lamb** [microsoft/vcrt-forwarders#19]
In the targets file for VCRT Forwarders, it checks for $(Configuration) == Release or Debug, explicitly by name.  This means that if i want to add a custom Configuration to my solution (like Debug-WithExtraStuff), I don't get the right files binplaced with the ReferenceLocalCopyPaths.

Please add some other property that can allow me to opt-in to the Debug/Release steps of the VCRT forwarder targets.  As an example, this line in the targets:

`<ItemGroup Condition="'$(Configuration)' == 'Debug' And ('$(Platform)' == 'Win32' Or '$(Platform)' == 'x86')">`

Could change to this:

`<ItemGroup Condition="'($(Configuration)' == 'Debug' Or $(VCRTForwarders-Configuration) == 'Debug') And ('$(Platform)' == 'Win32' Or '$(Platform)' == 'x86')">`

Then I could set that property in my custom configuration to get the same behavior as Debug or Release.

**Comment by manodasanW** [comment]
The flag we are checking might end up changing to _DEBUG (which is used by VS to determine which CRT to use apparently) which possibly could also end up solving this issue.
