### ISSUE TITLE
ARM and ARM64 libraries missing

### ISSUE THREAD

**Issue by Sudhaushu** [microsoft/vcrt-forwarders#2]
As the title says..
Is there a plan to also add ARM and ARM64 libraries?

**Comment by LPBourret** [comment]
Hi, @Huios any ETA or plans for releasing [VC redist](https://visualstudio.microsoft.com/downloads/) and forwarder for ARM and ARM64?

**Comment by Huios** [comment]
Hey folks, we're working on adding ARM and ARM64 versions. We'll send out the update as soon as they're ready.

**Comment by manodasanW** [comment]
Have PR out with ARM64 forwarders.  I didn't add any ARM forwarders as I wasn't able to find a vclibs redist for ARM.

**Comment by Sudhaushu** [comment]
I do see arm(32) redist in in my installation at VC\Redist\MSVC\14.16.27012\onecore\arm\Microsoft.VC141.CRT
Is this something we can utilize for the forwarders?

**Comment by manodasanW** [comment]
That is the app version I believe.  These forwarders forward from the app version to the desktop version of vclibs.  In order for that to work. there needs to be a version of vclibs that can be installed to something like system32.  And it doesn't look like VS is shipping such a version based on here.

![image](https://user-images.githubusercontent.com/1691134/59626342-77532800-90f0-11e9-9f56-5a2ebcd4496c.png)
